spring:
  application:
    name: buoi36
  datasource:
    url: jdbc:mysql://localhost:3307/buoi36
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  sql:
    init:
      mode: always
      platform: mysql
      encoding: UTF-8
      schema-locations: classpath:/schema.sql